/* AUTOGENERATED FILE.  DON'T EDIT ME! */

/* Copyright (C) 2024 Graham Bygrave
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the
 *   Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
package org.grating.recolldroid.data

import org.grating.recolldroid.R

enum class DocType(val text: String) {
    APPLICATION_EPUB_ZIP("application/epub+zip"),
    APPLICATION_JAVASCRIPT("application/javascript"),
    APPLICATION_MSWORD("application/msword"),
    APPLICATION_OGG("application/ogg"),
    APPLICATION_PDF("application/pdf"),
    APPLICATION_POSTSCRIPT("application/postscript"),
    APPLICATION_SQL("application/sql"),
    APPLICATION_X_IPYNB_JSON("application/x-ipynb+json"),
    APPLICATION_VND_MS_EXCEL("application/vnd.ms-excel"),
    APPLICATION_VND_MS_OFFICE("application/vnd.ms-office"),
    APPLICATION_VND_MS_OUTLOOK("application/vnd.ms-outlook"),
    APPLICATION_VND_MS_POWERPOINT("application/vnd.ms-powerpoint"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION("application/vnd.oasis.opendocument.presentation"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET("application/vnd.oasis.opendocument.spreadsheet"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT("application/vnd.oasis.opendocument.text"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_GRAPHICS("application/vnd.oasis.opendocument.graphics"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION_FLAT_XML("application/vnd.oasis.opendocument.presentation-flat-xml"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET_FLAT_XML("application/vnd.oasis.opendocument.spreadsheet-flat-xml"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT_FLAT_XML("application/vnd.oasis.opendocument.text-flat-xml"),
    APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT_TEMPLATE("application/vnd.oasis.opendocument.text-template"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION("application/vnd.openxmlformats-officedocument.presentationml.presentation"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_TEMPLATE("application/vnd.openxmlformats-officedocument.presentationml.template"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_TEMPLATE("application/vnd.openxmlformats-officedocument.spreadsheetml.template"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_TEMPLATE("application/vnd.openxmlformats-officedocument.wordprocessingml.template"),
    APPLICATION_VND_MS_VISIO_DRAWING("application/vnd.ms-visio.drawing"),
    APPLICATION_VND_SUN_XML_CALC("application/vnd.sun.xml.calc"),
    APPLICATION_VND_SUN_XML_CALC_TEMPLATE("application/vnd.sun.xml.calc.template"),
    APPLICATION_VND_SUN_XML_DRAW("application/vnd.sun.xml.draw"),
    APPLICATION_VND_SUN_XML_DRAW_TEMPLATE("application/vnd.sun.xml.draw.template"),
    APPLICATION_VND_SUN_XML_IMPRESS("application/vnd.sun.xml.impress"),
    APPLICATION_VND_SUN_XML_IMPRESS_TEMPLATE("application/vnd.sun.xml.impress.template"),
    APPLICATION_VND_SUN_XML_MATH("application/vnd.sun.xml.math"),
    APPLICATION_VND_SUN_XML_WRITER("application/vnd.sun.xml.writer"),
    APPLICATION_VND_SUN_XML_WRITER_GLOBAL("application/vnd.sun.xml.writer.global"),
    APPLICATION_VND_SUN_XML_WRITER_TEMPLATE("application/vnd.sun.xml.writer.template"),
    APPLICATION_VND_WORDPERFECT("application/vnd.wordperfect"),
    APPLICATION_X_7Z_COMPRESSED("application/x-7z-compressed"),
    APPLICATION_X_ABIWORD("application/x-abiword"),
    APPLICATION_X_AWK("application/x-awk"),
    APPLICATION_X_CHM("application/x-chm"),
    APPLICATION_X_DIA_DIAGRAM("application/x-dia-diagram"),
    APPLICATION_X_DVI("application/x-dvi"),
    APPLICATION_X_FLAC("application/x-flac"),
    AUDIO_X_FLAC("audio/x-flac"),
    AUDIO_FLAC("audio/flac"),
    APPLICATION_X_FSDIRECTORY("application/x-fsdirectory"),
    APPLICATION_X_GNOTE("application/x-gnote"),
    APPLICATION_X_GNUINFO("application/x-gnuinfo"),
    APPLICATION_X_GNUMERIC("application/x-gnumeric"),
    APPLICATION_X_KWORD("application/x-kword"),
    APPLICATION_X_LYX("application/x-lyx"),
    APPLICATION_X_MIMEHTML("application/x-mimehtml"),
    APPLICATION_X_MOBIPOCKET_EBOOK("application/x-mobipocket-ebook"),
    APPLICATION_X_OKULAR_NOTES("application/x-okular-notes"),
    APPLICATION_X_PERL("application/x-perl"),
    APPLICATION_X_PHP("application/x-php"),
    APPLICATION_X_RAR("application/x-rar"),
    APPLICATION_X_RUBY("application/x-ruby"),
    APPLICATION_X_SCRIBUS("application/x-scribus"),
    APPLICATION_X_SHELLSCRIPT("application/x-shellscript"),
    APPLICATION_X_TAR("application/x-tar"),
    APPLICATION_X_TEX("application/x-tex"),
    APPLICATION_X_WEBARCHIVE("application/x-webarchive"),
    APPLICATION_XML("application/xml"),
    APPLICATION_ZIP("application/zip"),
    AUDIO_AAC("audio/aac"),
    AUDIO_APE("audio/ape"),
    AUDIO_MP4("audio/mp4"),
    AUDIO_MPEG("audio/mpeg"),
    AUDIO_OGG("audio/ogg"),
    AUDIO_X_KARAOKE("audio/x-karaoke"),
    AUDIO_X_MUSEPACK("audio/x-musepack"),
    AUDIO_X_WAVPACK("audio/x-wavpack"),
    IMAGE_BMP("image/bmp"),
    IMAGE_GIF("image/gif"),
    IMAGE_JP2("image/jp2"),
    IMAGE_JPEG("image/jpeg"),
    IMAGE_PNG("image/png"),
    IMAGE_SVG_XML("image/svg+xml"),
    IMAGE_TIFF("image/tiff"),
    IMAGE_VND_DJVU("image/vnd.djvu"),
    IMAGE_X_NIKON_NEF("image/x-nikon-nef"),
    IMAGE_X_XCF("image/x-xcf"),
    IMAGE_X_XPMI("image/x-xpmi"),
    INODE_DIRECTORY("inode/directory"),
    INODE_SYMLINK("inode/symlink"),
    MESSAGE_RFC822("message/rfc822"),
    TEXT_CSS("text/css"),
    TEXT_HTML("text/html"),
    TEXT_HTML_CHM("text/html|chm"),
    TEXT_HTML_EPUB("text/html|epub"),
    TEXT_HTML_GNUINFO("text/html|gnuinfo"),
    TEXT_PLAIN("text/plain"),
    TEXT_RTF("text/rtf"),
    APPLICATION_RTF("application/rtf"),
    TEXT_X_BIBTEX("text/x-bibtex"),
    TEXT_X_C("text/x-c"),
    TEXT_X_C_("text/x-c+"),
    TEXT_X_C__("text/x-c++"),
    TEXT_X_CHM_HTML("text/x-chm-html"),
    TEXT_X_CSHARP("text/x-csharp"),
    TEXT_X_CSV("text/x-csv"),
    TEXT_X_FICTIONBOOK("text/x-fictionbook"),
    TEXT_X_HTML_APTOSID_MAN("text/x-html-aptosid-man"),
    TEXT_X_INI("text/x-ini"),
    TEXT_X_JAVA("text/x-java"),
    TEXT_X_LUA("text/x-lua"),
    TEXT_X_MAIL("text/x-mail"),
    TEXT_X_MAN("text/x-man"),
    TEXT_X_ORGMODE("text/x-orgmode"),
    TEXT_X_PERL("text/x-perl"),
    TEXT_X_PHP("text/x-php"),
    TEXT_X_PURPLE_HTML_LOG("text/x-purple-html-log"),
    TEXT_X_PURPLE_LOG("text/x-purple-log"),
    TEXT_X_PYTHON("text/x-python"),
    TEXT_X_RPM_SPEC("text/x-rpm-spec"),
    TEXT_X_RUBY("text/x-ruby"),
    TEXT_X_SHELLSCRIPT("text/x-shellscript"),
    TEXT_X_SRT("text/x-srt"),
    TEXT_X_TCL("text/x-tcl"),
    TEXT_X_TEX("text/x-tex"),
    TEXT_XML("text/xml"),
    VIDEO_3GPP("video/3gpp"),
    VIDEO_MP2P("video/mp2p"),
    VIDEO_MP2T("video/mp2t"),
    VIDEO_MP4("video/mp4"),
    VIDEO_MPEG("video/mpeg"),
    VIDEO_QUICKTIME("video/quicktime"),
    VIDEO_X_MATROSKA("video/x-matroska"),
    VIDEO_X_MS_ASF("video/x-ms-asf"),
    VIDEO_X_MSVIDEO("video/x-msvideo"),
    APPLICATION_JSON("application/json"),
    UNKNOWN("???");

    val typeIcon: Int
        get() = when (this) {
            APPLICATION_EPUB_ZIP -> R.drawable.book
            APPLICATION_JAVASCRIPT -> R.drawable.source
            APPLICATION_MSWORD -> R.drawable.wordprocessing
            APPLICATION_OGG -> R.drawable.sownd
            APPLICATION_PDF -> R.drawable.pdf
            APPLICATION_POSTSCRIPT -> R.drawable.postscript
            APPLICATION_SQL -> R.drawable.source
            APPLICATION_X_IPYNB_JSON -> R.drawable.document
            APPLICATION_VND_MS_EXCEL -> R.drawable.spreadsheet
            APPLICATION_VND_MS_OFFICE -> R.drawable.document
            APPLICATION_VND_MS_OUTLOOK -> R.drawable.document
            APPLICATION_VND_MS_POWERPOINT -> R.drawable.presentation
            APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION -> R.drawable.presentation
            APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET -> R.drawable.spreadsheet
            APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT -> R.drawable.wordprocessing
            APPLICATION_VND_OASIS_OPENDOCUMENT_GRAPHICS -> R.drawable.presentation
            APPLICATION_VND_OASIS_OPENDOCUMENT_PRESENTATION_FLAT_XML -> R.drawable.presentation
            APPLICATION_VND_OASIS_OPENDOCUMENT_SPREADSHEET_FLAT_XML -> R.drawable.spreadsheet
            APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT_FLAT_XML -> R.drawable.wordprocessing
            APPLICATION_VND_OASIS_OPENDOCUMENT_TEXT_TEMPLATE -> R.drawable.wordprocessing
            APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION -> R.drawable.presentation
            APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_TEMPLATE -> R.drawable.presentation
            APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET -> R.drawable.spreadsheet
            APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_TEMPLATE -> R.drawable.spreadsheet
            APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT -> R.drawable.wordprocessing
            APPLICATION_VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_TEMPLATE -> R.drawable.wordprocessing
            APPLICATION_VND_MS_VISIO_DRAWING -> R.drawable.document
            APPLICATION_VND_SUN_XML_CALC -> R.drawable.spreadsheet
            APPLICATION_VND_SUN_XML_CALC_TEMPLATE -> R.drawable.spreadsheet
            APPLICATION_VND_SUN_XML_DRAW -> R.drawable.drawing
            APPLICATION_VND_SUN_XML_DRAW_TEMPLATE -> R.drawable.drawing
            APPLICATION_VND_SUN_XML_IMPRESS -> R.drawable.presentation
            APPLICATION_VND_SUN_XML_IMPRESS_TEMPLATE -> R.drawable.presentation
            APPLICATION_VND_SUN_XML_MATH -> R.drawable.wordprocessing
            APPLICATION_VND_SUN_XML_WRITER -> R.drawable.wordprocessing
            APPLICATION_VND_SUN_XML_WRITER_GLOBAL -> R.drawable.wordprocessing
            APPLICATION_VND_SUN_XML_WRITER_TEMPLATE -> R.drawable.wordprocessing
            APPLICATION_VND_WORDPERFECT -> R.drawable.wordprocessing
            APPLICATION_X_7Z_COMPRESSED -> R.drawable.archive
            APPLICATION_X_ABIWORD -> R.drawable.wordprocessing
            APPLICATION_X_AWK -> R.drawable.source
            APPLICATION_X_CHM -> R.drawable.book
            APPLICATION_X_DIA_DIAGRAM -> R.drawable.drawing
            APPLICATION_X_DVI -> R.drawable.document
            APPLICATION_X_FLAC -> R.drawable.sownd
            AUDIO_X_FLAC -> R.drawable.sownd
            AUDIO_FLAC -> R.drawable.sownd
            APPLICATION_X_FSDIRECTORY -> R.drawable.folder
            APPLICATION_X_GNOTE -> R.drawable.document
            APPLICATION_X_GNUINFO -> R.drawable.book
            APPLICATION_X_GNUMERIC -> R.drawable.spreadsheet
            APPLICATION_X_KWORD -> R.drawable.wordprocessing
            APPLICATION_X_LYX -> R.drawable.wordprocessing
            APPLICATION_X_MIMEHTML -> R.drawable.message
            APPLICATION_X_MOBIPOCKET_EBOOK -> R.drawable.document
            APPLICATION_X_OKULAR_NOTES -> R.drawable.document
            APPLICATION_X_PERL -> R.drawable.source
            APPLICATION_X_PHP -> R.drawable.source
            APPLICATION_X_RAR -> R.drawable.archive
            APPLICATION_X_RUBY -> R.drawable.source
            APPLICATION_X_SCRIBUS -> R.drawable.wordprocessing
            APPLICATION_X_SHELLSCRIPT -> R.drawable.source
            APPLICATION_X_TAR -> R.drawable.archive
            APPLICATION_X_TEX -> R.drawable.wordprocessing
            APPLICATION_X_WEBARCHIVE -> R.drawable.archive
            APPLICATION_XML -> R.drawable.document
            APPLICATION_ZIP -> R.drawable.archive
            AUDIO_AAC -> R.drawable.sownd
            AUDIO_APE -> R.drawable.sownd
            AUDIO_MP4 -> R.drawable.sownd
            AUDIO_MPEG -> R.drawable.sownd
            AUDIO_OGG -> R.drawable.sownd
            AUDIO_X_KARAOKE -> R.drawable.sownd
            AUDIO_X_MUSEPACK -> R.drawable.sownd
            AUDIO_X_WAVPACK -> R.drawable.sownd
            IMAGE_BMP -> R.drawable.image
            IMAGE_GIF -> R.drawable.image
            IMAGE_JP2 -> R.drawable.image
            IMAGE_JPEG -> R.drawable.image
            IMAGE_PNG -> R.drawable.image
            IMAGE_SVG_XML -> R.drawable.drawing
            IMAGE_TIFF -> R.drawable.image
            IMAGE_VND_DJVU -> R.drawable.document
            IMAGE_X_NIKON_NEF -> R.drawable.image
            IMAGE_X_XCF -> R.drawable.image
            IMAGE_X_XPMI -> R.drawable.image
            INODE_DIRECTORY -> R.drawable.folder
            INODE_SYMLINK -> R.drawable.emblem_symbolic_link
            MESSAGE_RFC822 -> R.drawable.message
            TEXT_CSS -> R.drawable.html
            TEXT_HTML -> R.drawable.html
            TEXT_HTML_CHM -> R.drawable.bookchap
            TEXT_HTML_EPUB -> R.drawable.bookchap
            TEXT_HTML_GNUINFO -> R.drawable.bookchap
            TEXT_PLAIN -> R.drawable.txt
            TEXT_RTF -> R.drawable.wordprocessing
            APPLICATION_RTF -> R.drawable.wordprocessing
            TEXT_X_BIBTEX -> R.drawable.txt
            TEXT_X_C -> R.drawable.source
            TEXT_X_C_ -> R.drawable.source
            TEXT_X_C__ -> R.drawable.source
            TEXT_X_CHM_HTML -> R.drawable.html
            TEXT_X_CSHARP -> R.drawable.source
            TEXT_X_CSV -> R.drawable.txt
            TEXT_X_FICTIONBOOK -> R.drawable.book
            TEXT_X_HTML_APTOSID_MAN -> R.drawable.aptosid_book
            TEXT_X_INI -> R.drawable.txt
            TEXT_X_JAVA -> R.drawable.source
            TEXT_X_LUA -> R.drawable.source
            TEXT_X_MAIL -> R.drawable.message
            TEXT_X_MAN -> R.drawable.document
            TEXT_X_ORGMODE -> R.drawable.document
            TEXT_X_PERL -> R.drawable.source
            TEXT_X_PHP -> R.drawable.source
            TEXT_X_PURPLE_HTML_LOG -> R.drawable.pidgin
            TEXT_X_PURPLE_LOG -> R.drawable.pidgin
            TEXT_X_PYTHON -> R.drawable.text_x_python
            TEXT_X_RPM_SPEC -> R.drawable.source
            TEXT_X_RUBY -> R.drawable.source
            TEXT_X_SHELLSCRIPT -> R.drawable.source
            TEXT_X_SRT -> R.drawable.source
            TEXT_X_TCL -> R.drawable.source
            TEXT_X_TEX -> R.drawable.wordprocessing
            TEXT_XML -> R.drawable.document
            VIDEO_3GPP -> R.drawable.video
            VIDEO_MP2P -> R.drawable.video
            VIDEO_MP2T -> R.drawable.video
            VIDEO_MP4 -> R.drawable.video
            VIDEO_MPEG -> R.drawable.video
            VIDEO_QUICKTIME -> R.drawable.video
            VIDEO_X_MATROSKA -> R.drawable.video
            VIDEO_X_MS_ASF -> R.drawable.video
            VIDEO_X_MSVIDEO -> R.drawable.video
            APPLICATION_JSON -> R.drawable.txt

            UNKNOWN -> R.drawable.unknown_file_type
        }

    companion object {
        private val BY_TEXT = DocType.entries.associateBy({ it.text }, { it }) // <3

        fun byText(txt: String): DocType {
            return BY_TEXT[txt] ?: when {
                // Anything mapping out of the ordinary, put it here.
                else -> UNKNOWN
            }
        }
    }
}

data class MType(val docType: DocType, val rawType: String) {
    override fun toString(): String {
        return when (docType) {
            DocType.UNKNOWN -> rawType
            else -> {
                docType.toString()
            }
        }
    }

    companion object {
        val UNKNOWN: MType = MType(DocType.UNKNOWN, "UNKNOWN")
    }
}
